dist: trusty

language: node_js
node_js:
- 8

env:
- MOZ_HEADLESS=1

addons:
  firefox: latest

branches:
  only:
  - master

cache:
  directories:
  - "node_modules"

before_script:
- "cp src/environments/config.sample.ts src/environments/config.ts"
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3

script:
- npm run lint
- ng test --sr
- ng build --prod --base-href /

notifications:
  email:
    on_failure: change
    on_success: change


