language: node_js
node_js:
- 8
- 9

branches:
  only:
  - master
  - develop

cache:
  directories:
  - node_modules

install:
- npm install

script:
- npm run build

notifications:
  email:
    on_failure: never
    on_success: never
