sudo: required
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

language: node_js
node_js:
- 8
- 9

branches:
  only:
  - master
  - develop

cache:
  directories:
  - node_modules

before_script:
- npm install -g @angular/cli@latest
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3

install:
- npm install

script:
- npm run lint
- npm run test:sr
- npm run e2e
- npm run build

notifications:
  email:
    on_failure: never
    on_success: never
